### ISSUE TITLE
Bug: on PC, when going back from a show/movie details screen, it scrolls all the way to the top

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-shell#112]
Instead of just returning to where you've been before.

Steps: 
1. On "board", scroll down a bit and choose an item.
2. Press the arrow button on the top-left corner, to go back.

v4.4.77

**Comment by TRtomasz** [comment]
There is no arrow button in the top left corner in board

**Comment by AndroidDeveloperLB** [comment]
You forgot to read the rest of the sentence " and choose an item" .
The arrow button is here:

![image](https://user-images.githubusercontent.com/5357526/71769224-e9714a00-2f26-11ea-8429-53003c72d35f.png)

**Comment by Ivshti** [comment]
this looks like a spatial navigation auto-select bug @TRtomasz 

Pretty sure it reappeared at some point, since we already fixed that once

**Comment by AndroidDeveloperLB** [comment]
"spatial nav" ?

**Comment by Ivshti** [comment]
It's when you navigate with the arrow keys on the keyboard

**Comment by AndroidDeveloperLB** [comment]
Is it a common term, or only here?

**Comment by TRtomasz** [comment]
Looks like it is fixed now

**Comment by AndroidDeveloperLB** [comment]
@TRtomasz On which version? I have v4.4.120 on PC and it still occurs. Exact same issue.

Can you please share video of what you see?

**Comment by TRtomasz** [comment]
@AndroidDeveloperLB 
https://user-images.githubusercontent.com/40594253/111009012-60f00400-838a-11eb-9350-0b198fb75da6.mp4

**Comment by AndroidDeveloperLB** [comment]
@TRtomasz How odd. I think it doesn't always occur.
I really can reproduce it. Here, a video:
https://ufile.io/sq3444f3
Notice that in the beginning I failed, but in the end it happened.

**Comment by AndroidDeveloperLB** [comment]
@TRtomasz Please re-open this. It still occurs...
